runtime: node010

env:
  ROCK_NPM_SHRINKWRAP: "false"

run: exec node example.js

test: |
  if [[ -n "$ROCK_ARGV" ]]; then
    exec mocha --recursive --require should --reporter spec "${ARGV[@]}"
  else
    {{ parent }}
  fi
